; Enable pre-built PHP extensions shipped in the Devilbox PHP-FPM image

extension=pdo_mysql
extension=mysqli
extension=gd
extension=intl
extension=zip
extension=bcmath
extension=exif
extension=pcntl
