; PHP configuration mounted into the FPM containers at /usr/local/etc/php/conf.d

upload_max_filesize = 100M
post_max_size = 100M
memory_limit = 256M
max_execution_time = 300
max_input_vars = 3000

date.timezone = Asia/Manila

display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
